local use = require('packer').use
require('packer').startup(function()
  use  (require'.packer_config')
  use  (require'.lspconfig_config') 
  use  (require'.coq')
  use  (require'.coq3p')
  use  (require'.chad')
  use  (require'.telescope_config')
  use  (require'.lsplines')
  use  (require'.overseer_config')
  use  (require'.git')
  use  (require'.lspsaga_config')
  use  (require'.theme')
  use  (require'.rusttools')
end)
