theme = "bogster"

[editor]
line-number = "relative"
mouse = false
cursorline = true
bufferline = "multiple"
shell = ["powershell.exe", "-NoLogo", "-Command"]
default-line-ending = "lf"

[editor.cursor-shape]
insert = "bar"
select = "underline"

[editor.lsp]
display-inlay-hints = true
display-messages = true

[editor.file-picker]
hidden = false
git-ignore = false
