inherits = "bogster"


"variable.other.member" = "bogster-fg1"
"variable" = "bogster-fg1"
"variable.parameter" = "bogster-fg1"
"identifier" = "bogster-fg1"

"ui.virtual.inlay-hint" = "bogster-fg0" 

"ui.selection" = { bg = "bogster-base3" }
"ui.selection.primary" = { bg = "bogster-base4" }

"ui.virtual.jump-label" = { bg = "bogster-base3", modifiers = [ "bold" ] }
